[tool.poetry]
name = "tic-tac-toe"
version = "0.1.0"
description = ""
authors = ["Sergey Ilin <ilin_sergey90@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
